name: buildx

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
    paths:
      - ".github/workflows/buildx.yml"
      - "grafana/**"
      - "assets/**"
      - "config/**"
      - "lib/**"
      - "priv/**"
      - "mix.exs"
      - "mix.lock"
      - "entrypoint.sh"
      - "Dockerfile"
      - "VERSION"

jobs:
  teslamate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: teslamate/teslamate
          tags: |
            type=edge,
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-teslamate-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-teslamate-
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: teslamate
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  grafana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: teslamate/grafana
          tags: |
            type=edge,
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-grafana-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-grafana-
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: teslamate
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: grafana
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
